accounts/urls.py
"""为应用程序 accounts 定义 URL 模式"""
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    # 包含默认的身份验证 URL
    path('', include('django.contrib.auth.urls')),
    # 注册页面
    path('register/', views.register, name='register'),
]

il_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('investing_logs.urls')),

]

investing_logs/urls.py
"""定义 learning_logs 的 URL 模式"""
from django.urls import path
from . import views


app_name = 'investing_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 显示所有主题的页面
    path('instruments/', views.instruments, name='instruments'),
    # 特定主题的详细页面
    path('instruments/<int:instrument_id>/', views.instrument, name='instrument'),
    # 用于添加新主题的网页
    path('new_instrument/', views.new_instrument, name='new_instrument'),
    # 用于添加新条目的页面
    path('new_entry/<int:instrument_id>/', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

accounts/models.py
from django.db import models

# Create your models here.

investing_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Instrument(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """返回一个表示条目的简单字符串"""
        return f"{self.text[:50]}..."

investing_logs/forms.py
from django import forms
from .models import Instrument,Entry


class InstrumentForm(forms.ModelForm):
    class Meta:
        model = Instrument
        fields = ['text']
        labels = {'text': ''}



class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            login(request, new_user)
            return redirect('investing_logs:index')
    # 显示空表单或指出表单无效
    context = {'form': form}
    return render(request, 'registration/register.html',    context)

investing_logs/views.py
from django.shortcuts import render,redirect
from .models import Instrument, Entry
from .forms import InstrumentForm, EntryForm
import datetime
from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.
def index(request):
    """学习笔记的主页"""
    """学习笔记的主页"""
    current_time = datetime.datetime.now()
    context = {'current_time': current_time}
    return render(request, 'investing_logs/index.html',context)

@login_required
def instruments(request):
    """显示所有的主题"""
    instruments = Instrument.objects.filter(owner=request.user).order_by('date_added')
    context = {'instruments': instruments}
    return render(request, 'investing_logs/instruments.html',context)

@login_required
def instrument(request, instrument_id):
    """显示单个主题及其所有的条目"""
    instrument = Instrument.objects.get(id=instrument_id)
    # 确认请求的主题属于当前用户
    if instrument.owner != request.user:
        raise Http404
    entries = instrument.entry_set.order_by('-date_added')
    context = {'instrument': instrument, 'entries': entries}
    return render(request, 'investing_logs/instrument.html',context)

@login_required
def new_instrument(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = InstrumentForm()
    else:
        # POST 提交的数据：对数据进行处理
        form = InstrumentForm(data=request.POST)
        if form.is_valid():
            new_instrument = form.save(commit=False)
            new_instrument.owner = request.user
            new_instrument.save()

            return redirect('investing_logs:instruments')
    # 显示空表单或指出表单数据无效
    context = {'form': form}
    return render(request, 'investing_logs/new_instrument.html',context)

@login_required
def new_entry(request, instrument_id):
    """在特定主题中添加新条目"""
    instrument = Instrument.objects.get(id=instrument_id)
    if request.method != 'POST':
        # 未提交数据：创建一个空表单
        form = EntryForm()
    else:
        # POST 提交的数据：对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.instrument = instrument
            new_entry.save()
            return redirect('investing_logs:instrument', instrument_id=instrument_id)
    # 显示空表单或指出表单数据无效
    context = {'instrument': instrument, 'form': form}
    return render(request, 'investing_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """编辑既有的条目"""
    entry = Entry.objects.get(id=entry_id)
    instrument = entry.instrument
    if instrument.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # 初次请求：使用当前的条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST 提交的数据：对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('investing_logs:instrument', instrument_id=instrument.id)
    context = {'entry': entry, 'instrument': instrument, 'form': form}
    return render(request, 'investing_logs/edit_entry.html',    context)

investing_logs/templates/investing_logs/base.html
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=0.455, shrink-to-fit=no">
  <title>Investing Log</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
 <link rel="shortcut icon" href="#"/>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">

      <a class="navbar-brand" href="{% url 'investing_logs:index' %}">投资笔札InLog</a>
      <button class="navbar-toggler" type="button" data-bstoggle="collapse"
data-bs-target="#navbarCollapse" ariacontrols="navbarCollapse"aria-expanded="false" aria-label="Toggle
navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">

            <H1><a href="{% url 'investing_logs:instruments' %}">工具Instruments</a></H1> </li>
        </ul> <!-- 定义导航栏左侧链接的代码到此结束 -->

        <!-- 与账户相关的链接 -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text me-2">Hallo, {{user.username }}.
            </span>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}"> 注册Register
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">登录Login
              </a>
            </li>
          {% endif %}

        </ul> <!-- 与账户相关的链接到此结束 -->
        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outlinesecondary btn-sm'>
注销Log out</button>
          </form>
        {% endif %}




      </div> <!-- 定义导航栏可折叠部分的代码到此结束 -->

    </div> <!-- 定义导航栏容器的代码到此结束 -->
  </nav> <!-- 定义导航栏的代码到此结束 -->
  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
{% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>


</body>
</html>

investing_logs/templates/investing_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
</head>
<body>
  {% extends "investing_logs/base.html" %}
  {% block page_header %}
  <h1><a href="{% url 'investing_logs:instrument' instrument.id %}">{{instrument }}</a></h1>
   {% endblock page_header %}
  {% block content %}

    <p>编辑笔记Edit entry:</p>
    <form action="{% url 'investing_logs:edit_entry' entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_div }}
      <button name="submit">保存Save changes</button>
    </form>
  {% endblock content %}
</body>
</html>

investing_logs/templates/investing_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
<link rel="shortcut icon" href="#"/>
</head>
<body>
  {% extends 'investing_logs/base.html' %}
  {% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
      <div class="container-fluid py-4">
        <h1 class="display-3">Track your Investing & Learning.</h1>
        <p class="lead">Make your own Investing Log, and keep a
list of the topics you're investing about. Whenever you learn something new
about a topic, make an entry summarizing what you've learned.
        </p>
        <a class="btn btn-primary btn-lg mt-1"
href="{% url 'accounts:register' %}">注册Register &raquo;
        </a>
      </div>
    </div>
  {% endblock page_header %}




  {% block content %}
  {% load static %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <img style="max-width:100%;overflow:hidden;" src="{% static 'images/卢浮宫.jpg' %}" alt="Your Image Description" >
        <p></p>
      <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
          <p>日日新，又日新，苟日新。 </p>
          <p>Investing Log helps you renew yourself day by day; </p>
          <p> make it new again, and again, and yet again.</p>
          <p>  ©InLog by Hsing.Leo @Asia/Shanghai</p>
          <p> {{current_time}}</p>
        </div>
      </div>

  </div>

  {% endblock content %}
</body>
</html>

investing_logs/templates/investing_logs/instrument.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
</head>
<body>
  {% extends 'investing_logs/base.html' %}

  {% block page_header %}
    <h1>{{ instrument.text }}</h1>
  {% endblock page_header %}

  {% block content %}
    <br>
    <H2><a href="{% url 'investing_logs:new_entry' instrument.id %}">添加笔记Add a new entry</a></H2>
    <br>
    <br>

    {% for entry in entries %}
      <div class="card mb-3">
        <!-- 包含时间戳和编辑链接的标题 -->
        <h4 class="card-header">

          {{ entry.date_added|date:'M d, Y H:i' }}


           <a href="{% url 'investing_logs:edit_entry' entry.id %}">编辑笔记Edit entry</a>
        </h4>
        <!-- 包含条目文本的正文 -->
        <h2><div class="card-body">{{ entry.text|linebreaks }}</div></h2>
      </div>
    {% empty %}
      <p>There are no entries for this topic yet.</p>

    {% endfor %}

  {% endblock content %}
</body>
</html>

investing_logs/templates/investing_logs/instruments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
    <link rel="shortcut icon" href="#"/>
</head>
<body>
  {% extends 'investing_logs/base.html' %}
  {% block page_header %}
     <h1>工具Instruments</h1>
  {% endblock page_header %}

  {% block content %}

    <ul>
      {% for instrument in instruments %}
        <br>
        <br>
      <li class="list-group-item border-0">
          <H1><a href="{% url 'investing_logs:instrument' instrument.id %}">  {{ instrument.text }}</a></H1>

          <br>

      </li>
      {% empty %}
        <li class="list-group-item border-0" >No topics have been added yet.</li>
      {% endfor %}
      </ul>
      <br>
       <H2><a href="{% url 'investing_logs:new_instrument' %}">添加工具Add a new instrument</a></H2>

  {% endblock content %}


</body>
</html>

investing_logs/templates/investing_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>

</head>
<body>
  {% extends "investing_logs/base.html" %}
  {% block page_header %}
  <h1>
  <a href="{% url 'investing_logs:instrument' instrument.id %}">{{instrument}}</a>
  </h1>
  {% endblock page_header %}

  {% block content %}
  <br>
  <p>添加笔记Add a new entry:</p>
  <br>
  <form action="{% url 'investing_logs:new_entry' instrument.id%}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>添加Add entry</button>
    </form>
  {% endblock content %}
</body>
</html>

investing_logs/templates/investing_logs/new_instrument.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
</head>
<body>
  {% extends "investing_logs/base.html" %}
  {% block page_header %}
  <p>添加工具Add a new instrument:</p>
  {% endblock page_header %}
  {% block content %}

  <form action="{% url 'investing_logs:new_instrument' %}" method='post'>
  {% csrf_token %}
  {{ form.as_div }}
      <BR>
  <button name="submit">添加Add</button>
</form>
{% endblock content %}
</body>
</html>